### ISSUE TITLE
Add/delete Rows:  Dropdown is currently unusable

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#527]
## Description

There is no way for users to get to this functionality unless we fix the dropdown overlay issue. Is it a z index issue?

## Version
Data-grid: Branch feature/item-action
Browser: Chrome

## Screenshot
![screen shot 2018-01-26 at 2 10 43 pm](https://user-images.githubusercontent.com/10835611/35463212-6653fc9a-02a4-11e8-86b6-bc3bf6da9bce.png)

**Comment by alump** [comment]
This issue is purely in px-dropdown.

**Comment by alump** [comment]
Notice, this issue is reported from branch feature/item-action

**Comment by toshegg** [comment]
This isn't a `z-index` issue. This issue is because each row in vaadin-grid has it's own stacking context, so px-dropdown's overlay is relative to the row. 
To fix this issue you need to move your overlays to document body, as it is done in https://github.com/vaadin/vaadin-overlay.

**Comment by alump** [comment]
Even with z-index the dropdown will be cut by scrollable area, so no point to start adjusting z-index. It needs proper fix.

**Comment by Aileen-H** [comment]
PRIORITY 1 - GE will fix overlay issue so this can be fixed.

**Comment by ppeyro** [comment]
Just an additional note.
In the latest tagV1.1.9, looks like the dropdown is completely hidden underneath the grid. Initially, I thought  the dropdown was totally broken, but Sami pointed out that it's visible on the last row. tucked in underneath the grid. 

![screen shot 2018-02-01 at 12 40 52 pm](https://user-images.githubusercontent.com/10835611/35702253-789ea47e-074d-11e8-85f9-efd116d3eb01.png)

**Comment by alump** [comment]
We are still waiting for version of px-dropdown that will attach the dropdown to body (and not to same DOM level where dropdown button is). Before this dropdowns will not work correctly inside grid (scrolling container and parent clipping).

**Comment by ppeyro** [comment]
Additional Note:
In V1.1.11, with the latest modal fixes picked up, this is now affecting the dropdown in the filtering modal as well.

![screen shot 2018-02-06 at 4 17 01 pm](https://user-images.githubusercontent.com/10835611/35891927-892d4626-0b5b-11e8-9f73-dd2f36dabb0d.png)

**Comment by nonmetalhail** [comment]
fixed in dropdown v4.6.x

**Comment by limonte** [comment]
> fixed in dropdown v4.6.x

@nonmetalhail nope, still doesn't work properly:

![](https://i.imgur.com/3xRuWuu.png)

Steps to reproduce:

- clone https://github.com/vaadin/px-data-grid
- `yarn && bower install`
- `gulp serve`
- check out the basic examples

**Comment by nonmetalhail** [comment]
You have not applied the `hoist` property to the dropdown. You need to apply the `hoist` property. and then it will escape your stacking context.

![screen shot 2018-02-27 at 9 36 16 am](https://user-images.githubusercontent.com/1649404/36744458-c065c888-1ba1-11e8-913a-a107aaf58599.png)
