### ISSUE TITLE
After the px-dropdown update advanced filter layout is broken

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#702]
The new version of px-dropdown was released 2 days ago: https://github.com/PredixDev/px-dropdown/releases/tag/v4.6.0
 
Looks like the styles for `px-overlay-content` are missing:
 
![](https://i.imgur.com/G6g95Gs.png)

@nonmetalhail any idea what should be done?

**Comment by nonmetalhail** [comment]
I cannot replicate this issue; can you provide recreation steps?

**Comment by nonmetalhail** [comment]
Ok, this has been fixed. Reinstall. But this was also only occurring with the hoist property off on dropdown which was the reason of delivering this change to you

**Comment by limonte** [comment]
> Ok, this has been fixed. Reinstall.

@nonmetalhail Reinstalled, still the same issue.

Steps to reproduce: 

- clone https://github.com/vaadin/px-data-grid
- `yarn && bower install`
- `gulp serve`
- check out the basic examples
- turn on the 'filterable' setting from the left sidebar
- click the 'Table filters' button

---

Could you please attach the link to a release/PR/commit in which you think the issue has been fixed?

**Comment by nonmetalhail** [comment]
This spacing does not appear to be due to dropdown. You apply a 33% width to your div. Removing that width makes the space disappear.

## px-overlay-content size
![screen shot 2018-02-27 at 9 28 08 am](https://user-images.githubusercontent.com/1649404/36744170-facc0754-1ba0-11e8-80b5-29e267cafa44.png)

## Surrounding div
![screen shot 2018-02-27 at 9 29 34 am](https://user-images.githubusercontent.com/1649404/36744207-0ec2932c-1ba1-11e8-9cd4-2231b81dc0fb.png)

<img width="941" alt="screen shot 2018-02-27 at 9 29 41 am" src="https://user-images.githubusercontent.com/1649404/36744209-12168088-1ba1-11e8-8a03-ca90cf416b9d.png">

**Comment by alump** [comment]
No, we define width of px-dropdown for a reason to be 33%, the issue is that px-dropdown does not anymore respect size given to it. So just make px-dropdown, set it's width 100% in css, and see that dropdown doesn't fill the space. Is there some way to ask px-dropdown to respect the size given to it?

**Comment by nonmetalhail** [comment]
ok, someone on our end will take a look

**Comment by randyaskin** [comment]
I believe I've fixed this in v4.7.3 - it's fixed things throughout our demo pages at least.

**Comment by drewharvey** [comment]
Confirm that this has been fixed with latest px-dropdown.
